import "@src/styles/globals.css";

import Head from "next/head";
import { Hero } from "@src/components/molecules/Hero";
import { DataSection } from "@src/components/molecules/DataSection";
import { PERSONAL_INFO } from "@src/constants";
import { PersonalInfo } from "@src/components/molecules/PersonalInfo";
import { SkillSet } from "@src/components/atoms/SkillSet";
import { WorkExperience } from "@src/components/molecules/WorkExperience";
import { FeaturedProjects } from "@src/components/molecules/FeaturedProjects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-5 md:gap-9">
        <Hero />
        <PersonalInfo />

        <DataSection title="About">{PERSONAL_INFO.ABOUT.content}</DataSection>

        <DataSection title="Tech Stack">
          <SkillSet />
        </DataSection>

        <DataSection title="Work Experience">
          <WorkExperience />
        </DataSection>

        <DataSection title="Featured Projects">
          <FeaturedProjects />
        </DataSection>
      </div>
    </>
  );
}
